{
 "title": "Nice dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "# of running K8s Nodes",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_node_name{job=\"kubernetes-nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity of CPU activity per Nodes",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"kubernetes-nodes\"}[2m])*1000"
    }
   ]
  },
  {
   "title": "Running Containers",
   "type": "stat",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kubelet_running_containers{job=\"kubernetes-nodes\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flask-app Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{app=\"flask-webapp\"} |~ `ERROR|INFO|WARNING`"
    }
   ]
  },
  {
   "title": "Number of Shutdowns",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"flask-webapp\"} |~ \"Shutting\"[5m]))"
    }
   ]
  }
 ]
}